all:
	mex -O klr_addsigsq.c
	mex -O klr_compkernmatvect.c
	mex -O klr_compmatphit.c
	mex -O klr_compkernmatmat.c
	mex -O klr_compkernmatvect_lr.c
	mex -O klr_compmatvect.c
	mex -O klr_compkernmatmat_lr.c
	mex -O klr_compmatphi.c
	mex -O klr_mexmulv.c
